-- ==============================================================================
-- 🚀 SKRIP SETUP DATABASE SUPABASE LENGKAP & PRESISI
-- SESUAI STRUKTUR TABEL & DATA RIIL SISTEM PERMINTAAN TOKO
-- ==============================================================================
-- CARA PENGGUNAAN:
-- 1. Buka Dashboard Supabase Anda (https://supabase.com/dashboard)
-- 2. Pilih Proyek Baru Anda -> Klik menu "SQL Editor" di bilah kiri
-- 3. Klik tombol "+ New query"
-- 4. Salin (Copy) & Tempel (Paste) seluruh kode SQL di bawah ini, lalu klik "RUN"
-- ==============================================================================

-- 1. TABEL: USERS (PENGGUNA LENGKAP DENGAN KOLOM THEME)
CREATE TABLE IF NOT EXISTS public.users (
    id TEXT PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL DEFAULT '1',
    full_name TEXT NOT NULL,
    store_code TEXT DEFAULT '',
    phone TEXT DEFAULT '-',
    category TEXT NOT NULL DEFAULT 'TOKO',
    area TEXT NOT NULL DEFAULT 'BDG',
    can_print_pdf BOOLEAN DEFAULT false,
    can_upload_bukti BOOLEAN DEFAULT true,
    theme TEXT DEFAULT '',
    created_at TEXT DEFAULT '',
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS can_print_pdf BOOLEAN DEFAULT false;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS can_upload_bukti BOOLEAN DEFAULT true;

-- 2. TABEL: LOOKUP (ID AUTO INCREMENT, KEY, VALUE, TYPE, UPDATED_AT)
CREATE TABLE IF NOT EXISTS public.lookup (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    value JSONB DEFAULT '{}'::jsonb,
    type TEXT DEFAULT '',
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. TABEL: TOKO_LIST (DAFTAR TOKO RESMI)
CREATE TABLE IF NOT EXISTS public.toko_list (
    id TEXT PRIMARY KEY,
    full_name TEXT NOT NULL,
    store_code TEXT DEFAULT '',
    area TEXT NOT NULL DEFAULT 'BDG',
    created_by TEXT DEFAULT 'ADMIN',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. TABEL: PERMINTAAN_TOKO (TRANSAKSI SURAT PERMINTAAN & APPROVAL)
CREATE TABLE IF NOT EXISTS public.permintaan_toko (
    id TEXT PRIMARY KEY,
    no_surat TEXT UNIQUE NOT NULL,
    tanggal TEXT DEFAULT '',
    toko TEXT DEFAULT '',
    area TEXT DEFAULT 'BDG',
    jenis TEXT DEFAULT 'DEFAULT',
    catatan TEXT DEFAULT '',
    items JSONB DEFAULT '[]'::jsonb,
    photos JSONB DEFAULT '[]'::jsonb,
    artemis_photos JSONB DEFAULT '[]'::jsonb,
    status TEXT DEFAULT 'PENDING',
    service_approve BOOLEAN DEFAULT false,
    service_user_name TEXT DEFAULT '',
    service_ttd TEXT DEFAULT '',
    dm_user_name TEXT DEFAULT '',
    dm_ttd TEXT DEFAULT '',
    pemohon_ttd TEXT DEFAULT '',
    created_by TEXT DEFAULT '',
    created_at TEXT DEFAULT '',
    user_id TEXT DEFAULT '',
    log JSONB DEFAULT '[]'::jsonb,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- 5. ROW LEVEL SECURITY (RLS) & KEBIJAKAN AKSES PENUH (ANON & AUTHENTICATED)
-- ==============================================================================
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lookup ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.toko_list ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.permintaan_toko ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public full access users" ON public.users;
CREATE POLICY "Public full access users" ON public.users FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public full access lookup" ON public.lookup;
CREATE POLICY "Public full access lookup" ON public.lookup FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public full access toko_list" ON public.toko_list;
CREATE POLICY "Public full access toko_list" ON public.toko_list FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public full access permintaan_toko" ON public.permintaan_toko;
CREATE POLICY "Public full access permintaan_toko" ON public.permintaan_toko FOR ALL USING (true) WITH CHECK (true);

-- ==============================================================================
-- 6. PUBLIKASI REALTIME SUPABASE UNTUK SEMUA TABEL
-- ==============================================================================
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND tablename = 'permintaan_toko'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.permintaan_toko;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND tablename = 'users'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.users;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND tablename = 'toko_list'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.toko_list;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND tablename = 'lookup'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.lookup;
    END IF;
END $$;

-- ==============================================================================
-- 7. STORAGE BUCKET: BIKIN BUCKET 'photos' UNTUK FOTO PERMINTAAN & TTD
-- ==============================================================================
INSERT INTO storage.buckets (id, name, public)
VALUES ('photos', 'photos', true)
ON CONFLICT (id) DO UPDATE SET public = true;

DROP POLICY IF EXISTS "Public Access Photos" ON storage.objects;
CREATE POLICY "Public Access Photos" ON storage.objects FOR ALL USING (bucket_id = 'photos') WITH CHECK (bucket_id = 'photos');

-- ==============================================================================
-- 8. SEED DATA LENGKAP PENGGUNA (USERS ASLI SISTEM)
-- ==============================================================================
INSERT INTO public.users (id, username, password, full_name, store_code, phone, category, area, theme, created_at)
VALUES 
    ('USR-1786503880831-701', 'DM', '1', 'FERRY EDIYANTO', 'BFE', '6281313665599', 'DM', 'ALL', '', '12/08/2026'),
    ('USR-1786518085185-694', 'GBJ', '1', 'GUDANG BARANG JADI (GBJ BDG)', 'GB', '-', 'GBJ', 'BDU', '', '12/08/2026'),
    ('USR-1786518803076-850', 'KIM', '1', 'RONI SURYA NUGRAHA', 'RSN', '082322494191', 'SALES', 'TSM', '', '12/08/2026'),
    ('USR-1786519280585-433', 'SKB', '1', 'DIMAS ARBIANSYAH', 'DA', '085723555782', 'SERVICE', 'SKB', '', '12/08/2026'),
    ('USR-1786520232536-457', 'BDU', '1', 'M.AWALUDDIN.R', 'AW', '089656048848', 'SERVICE', 'BDU', '', '12/08/2026'),
    ('USR-1786522916571-262', 'HERRY KURNIAWAN', '1', 'HERRY KURNIAWAN', 'HK', '628122358255', 'SALES', 'BDU', '', '12/08/2026'),
    ('USR-1786522952567-286', 'DJONNY HARIAWAN', '1', 'DJONNY HARIAWAN', 'DH', '62811209557', 'SALES', 'BDU, SKB', '', '12/08/2026'),
    ('USR-1786523012123-342', 'ROBBY WATARI', '1', 'ROBBY WATARI', 'RW', '628156058566', 'SALES', 'BDU', '', '12/08/2026'),
    ('USR-1786523052945-595', 'SING FAT', '1', 'SING FAT', 'SF', '6285720000980', 'SALES', 'BDU, TSM', '', '12/08/2026'),
    ('USR-1786523087208-373', 'HARDY TANURAHARDJA', '1', 'HARDY TANURAHARDJA', 'HT', '6281383407685', 'SALES', 'BDU, CRB', '', '12/08/2026'),
    ('USR-1786523118870-647', 'ANDRI GUNAWAN', '1', 'ANDRI GUNAWAN', 'AG', '6287729133816', 'SALES', 'BDU, CRB', '', '12/08/2026'),
    ('USR-1786584873337-351', 'CRB', '1', 'SUMARWAN', 'SU', '081809693898', 'SERVICE', 'CRB', '', '13/08/2026'),
    ('USR-1786584921101-816', 'SBN', '1', 'DARWANTO', 'DR', '085201433549', 'SERVICE', 'SBN', '', '13/08/2026'),
    ('USR-1787124294394-416', 'TSM', '1', 'BAUT ADHI WISMANTORO', 'BAW', '120363424747010987@g.us', 'SERVICE', 'TSM', 'dark-mode', '19/08/2026'),
    ('USR-ADMIN', 'ADMIN', '000', 'SUPER ADMIN', '', '-', 'ADMIN', 'ALL', '', '31/07/2026')
ON CONFLICT (username) DO UPDATE SET
    password = EXCLUDED.password,
    full_name = EXCLUDED.full_name,
    store_code = EXCLUDED.store_code,
    phone = EXCLUDED.phone,
    category = EXCLUDED.category,
    area = EXCLUDED.area,
    theme = EXCLUDED.theme;

-- ==============================================================================
-- 9. SEED DATA AWAL: TABEL LOOKUP (FONTE TOKEN & FEATURE PHOTOS)
-- ==============================================================================
INSERT INTO public.lookup (key, value, type)
VALUES 
    ('fonteToken', '"TESFejqMMmJNpcfvouaqVoE"'::jsonb, ''),
    ('FEATURE_PHOTOS', '{"enabled":"true"}'::jsonb, '')
ON CONFLICT (key) DO UPDATE SET
    value = EXCLUDED.value;

-- ==============================================================================
-- 10. INDEKS OPTIMASI QUERY
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_permintaan_toko_no_surat ON public.permintaan_toko (no_surat);
CREATE INDEX IF NOT EXISTS idx_permintaan_toko_toko ON public.permintaan_toko (toko);
CREATE INDEX IF NOT EXISTS idx_permintaan_toko_area ON public.permintaan_toko (area);
CREATE INDEX IF NOT EXISTS idx_permintaan_toko_status ON public.permintaan_toko (status);
CREATE INDEX IF NOT EXISTS idx_users_username ON public.users (username);
CREATE INDEX IF NOT EXISTS idx_toko_list_area ON public.toko_list (area);

-- ==============================================================================
-- ✅ SELESAI! STRUKTUR TABEL & DATA LENGKAP 100% SIAP DIGUNAKAN!
-- ==============================================================================
